[tool.poetry]
name = "pyloras"
version = "0.1.0"
description = "LoRAS: An oversampling approach for imbalanced datasets"
authors = ["Zolisa Bleki <zolisa.bleki@gmail.com>"]
license = "BSD-3-Clause"
readme = 'README.md'
keywords = [
    'imbalanced datasets',
    'oversampling',
    'machine learning',
    'localized affine random shadowsampling'
]

[tool.poetry.dependencies]
python = "^3.6"
imbalanced-learn = "^0.7.0"

[tool.poetry.dev-dependencies]
imbalanced-learn = "^0.7.0"
pytest-cov = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
